# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Projects
email: tiagoaf@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this page my goal is to present some projects I was involved in the last years.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tiagoaf5.github.io" # the base hostname & protocol for your site
linkedin_username: tiagoalmeidafernandes
github_username:  tiagoaf5

# Build settings
markdown: kramdown
